//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import RswiftResources

private class BundleFinder {}
let R = _R(bundle: Bundle(for: BundleFinder.self))

struct _R {
  let bundle: Foundation.Bundle
  var string: string { .init(bundle: bundle, preferredLanguages: nil, locale: nil) }
  var color: color { .init(bundle: bundle) }
  var image: image { .init(bundle: bundle) }
  var info: info { .init(bundle: bundle) }
  var file: file { .init(bundle: bundle) }

  func string(bundle: Foundation.Bundle) -> string {
    .init(bundle: bundle, preferredLanguages: nil, locale: nil)
  }
  func string(locale: Foundation.Locale) -> string {
    .init(bundle: bundle, preferredLanguages: nil, locale: locale)
  }
  func string(preferredLanguages: [String], locale: Locale? = nil) -> string {
    .init(bundle: bundle, preferredLanguages: preferredLanguages, locale: locale)
  }
  func color(bundle: Foundation.Bundle) -> color {
    .init(bundle: bundle)
  }
  func image(bundle: Foundation.Bundle) -> image {
    .init(bundle: bundle)
  }
  func info(bundle: Foundation.Bundle) -> info {
    .init(bundle: bundle)
  }
  func file(bundle: Foundation.Bundle) -> file {
    .init(bundle: bundle)
  }
  func validate() throws {

  }

  struct project {
    let developmentRegion = "en"
  }

  /// This `_R.string` struct is generated, and contains static references to 1 localization tables.
  struct string {
    let bundle: Foundation.Bundle
    let preferredLanguages: [String]?
    let locale: Locale?
    var localizable: localizable { .init(source: .init(bundle: bundle, tableName: "Localizable", preferredLanguages: preferredLanguages, locale: locale)) }

    func localizable(preferredLanguages: [String]) -> localizable {
      .init(source: .init(bundle: bundle, tableName: "Localizable", preferredLanguages: preferredLanguages, locale: locale))
    }


    /// This `_R.string.localizable` struct is generated, and contains static references to 55 localization keys.
    struct localizable {
      let source: RswiftResources.StringResource.Source

      /// Value: Add
      ///
      /// Key: add
      var add: RswiftResources.StringResource { .init(key: "add", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Add a photo
      ///
      /// Key: addPhoto
      var addPhoto: RswiftResources.StringResource { .init(key: "addPhoto", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Add a workout
      ///
      /// Key: addWorkout
      var addWorkout: RswiftResources.StringResource { .init(key: "addWorkout", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Back
      ///
      /// Key: back
      var back: RswiftResources.StringResource { .init(key: "back", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Cancel
      ///
      /// Key: cancel
      var cancel: RswiftResources.StringResource { .init(key: "cancel", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Thank you for choosing us!
      ///
      /// Key: chooseLabel
      var chooseLabel: RswiftResources.StringResource { .init(key: "chooseLabel", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Train at any time and keep track of your progress
      ///
      /// Key: chooseSubLabel
      var chooseSubLabel: RswiftResources.StringResource { .init(key: "chooseSubLabel", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Close
      ///
      /// Key: close
      var close: RswiftResources.StringResource { .init(key: "close", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Delete
      ///
      /// Key: delete
      var delete: RswiftResources.StringResource { .init(key: "delete", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Delete Photo
      ///
      /// Key: deletePhoto
      var deletePhoto: RswiftResources.StringResource { .init(key: "deletePhoto", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Do you really want to delete this?
      ///
      /// Key: deleteThis
      var deleteThis: RswiftResources.StringResource { .init(key: "deleteThis", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Description
      ///
      /// Key: description
      var description: RswiftResources.StringResource { .init(key: "description", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Edit
      ///
      /// Key: edit
      var edit: RswiftResources.StringResource { .init(key: "edit", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Edit Photo
      ///
      /// Key: editPhoto
      var editPhoto: RswiftResources.StringResource { .init(key: "editPhoto", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Edit Workout
      ///
      /// Key: editWorkout
      var editWorkout: RswiftResources.StringResource { .init(key: "editWorkout", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Further
      ///
      /// Key: further
      var further: RswiftResources.StringResource { .init(key: "further", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Let's get started
      ///
      /// Key: getStarted
      var getStarted: RswiftResources.StringResource { .init(key: "getStarted", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Health
      ///
      /// Key: health
      var health: RswiftResources.StringResource { .init(key: "health", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Number calories
      ///
      /// Key: healthCalories
      var healthCalories: RswiftResources.StringResource { .init(key: "healthCalories", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Pulse
      ///
      /// Key: healthPulse
      var healthPulse: RswiftResources.StringResource { .init(key: "healthPulse", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Sleep
      ///
      /// Key: healthSleep
      var healthSleep: RswiftResources.StringResource { .init(key: "healthSleep", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Weight
      ///
      /// Key: healthWeight
      var healthWeight: RswiftResources.StringResource { .init(key: "healthWeight", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Height
      ///
      /// Key: height
      var height: RswiftResources.StringResource { .init(key: "height", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Height of the tape
      ///
      /// Key: heightTape
      var heightTape: RswiftResources.StringResource { .init(key: "heightTape", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Home
      ///
      /// Key: home
      var home: RswiftResources.StringResource { .init(key: "home", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Main
      ///
      /// Key: main
      var main: RswiftResources.StringResource { .init(key: "main", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Maximum distance
      ///
      /// Key: maxDistance
      var maxDistance: RswiftResources.StringResource { .init(key: "maxDistance", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Maximum height
      ///
      /// Key: maxHeight
      var maxHeight: RswiftResources.StringResource { .init(key: "maxHeight", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Mood during training
      ///
      /// Key: moodTraining
      var moodTraining: RswiftResources.StringResource { .init(key: "moodTraining", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Get better, stay motivated.
      ///
      /// Key: motivatedSubLabel
      var motivatedSubLabel: RswiftResources.StringResource { .init(key: "motivatedSubLabel", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Name
      ///
      /// Key: name
      var name: RswiftResources.StringResource { .init(key: "name", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: New Workout
      ///
      /// Key: newWorkout
      var newWorkout: RswiftResources.StringResource { .init(key: "newWorkout", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: No data
      ///
      /// Key: noData
      var noData: RswiftResources.StringResource { .init(key: "noData", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Number of training sessions
      ///
      /// Key: numberTraining
      var numberTraining: RswiftResources.StringResource { .init(key: "numberTraining", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Progress
      ///
      /// Key: progress
      var progress: RswiftResources.StringResource { .init(key: "progress", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Progress in a month
      ///
      /// Key: progressMonth
      var progressMonth: RswiftResources.StringResource { .init(key: "progressMonth", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Rate app
      ///
      /// Key: rateApp
      var rateApp: RswiftResources.StringResource { .init(key: "rateApp", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Reset progress
      ///
      /// Key: reset
      var reset: RswiftResources.StringResource { .init(key: "reset", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Save
      ///
      /// Key: save
      var save: RswiftResources.StringResource { .init(key: "save", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Settings
      ///
      /// Key: settings
      var settings: RswiftResources.StringResource { .init(key: "settings", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Share app
      ///
      /// Key: shareApp
      var shareApp: RswiftResources.StringResource { .init(key: "shareApp", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Skip
      ///
      /// Key: skip
      var skip: RswiftResources.StringResource { .init(key: "skip", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Slackline Tracker
      ///
      /// Key: slacklineTracker
      var slacklineTracker: RswiftResources.StringResource { .init(key: "slacklineTracker", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Time
      ///
      /// Key: time
      var time: RswiftResources.StringResource { .init(key: "time", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: To track progress
      ///
      /// Key: trackProgress
      var trackProgress: RswiftResources.StringResource { .init(key: "trackProgress", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Training
      ///
      /// Key: training
      var training: RswiftResources.StringResource { .init(key: "training", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Training photos
      ///
      /// Key: trainingPhotos
      var trainingPhotos: RswiftResources.StringResource { .init(key: "trainingPhotos", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Training place
      ///
      /// Key: trainingPlace
      var trainingPlace: RswiftResources.StringResource { .init(key: "trainingPlace", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Training time
      ///
      /// Key: trainingTime
      var trainingTime: RswiftResources.StringResource { .init(key: "trainingTime", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Type of tape
      ///
      /// Key: typeTape
      var typeTape: RswiftResources.StringResource { .init(key: "typeTape", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Usage Policy
      ///
      /// Key: usagePolicy
      var usagePolicy: RswiftResources.StringResource { .init(key: "usagePolicy", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Value
      ///
      /// Key: value
      var value: RswiftResources.StringResource { .init(key: "value", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Welcome
      ///
      /// Key: welcome
      var welcome: RswiftResources.StringResource { .init(key: "welcome", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: An application for recording and tracking slackline workouts
      ///
      /// Key: welcomeSubLabel
      var welcomeSubLabel: RswiftResources.StringResource { .init(key: "welcomeSubLabel", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Wind speed
      ///
      /// Key: windSpeed
      var windSpeed: RswiftResources.StringResource { .init(key: "windSpeed", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }
    }
  }

  /// This `_R.color` struct is generated, and contains static references to 1 colors.
  struct color {
    let bundle: Foundation.Bundle

    /// Color `AccentColor`.
    var accentColor: RswiftResources.ColorResource { .init(name: "AccentColor", path: [], bundle: bundle) }
  }

  /// This `_R.image` struct is generated, and contains static references to 23 images.
  struct image {
    let bundle: Foundation.Bundle

    /// Image `health_calories_icon`.
    var health_calories_icon: RswiftResources.ImageResource { .init(name: "health_calories_icon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `health_down`.
    var health_down: RswiftResources.ImageResource { .init(name: "health_down", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `health_pulse_icon`.
    var health_pulse_icon: RswiftResources.ImageResource { .init(name: "health_pulse_icon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `health_sleep_icon`.
    var health_sleep_icon: RswiftResources.ImageResource { .init(name: "health_sleep_icon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `health_up`.
    var health_up: RswiftResources.ImageResource { .init(name: "health_up", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `health_weight_icon`.
    var health_weight_icon: RswiftResources.ImageResource { .init(name: "health_weight_icon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `home_height_icon`.
    var home_height_icon: RswiftResources.ImageResource { .init(name: "home_height_icon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `home_placeholder`.
    var home_placeholder: RswiftResources.ImageResource { .init(name: "home_placeholder", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `home_training_icon`.
    var home_training_icon: RswiftResources.ImageResource { .init(name: "home_training_icon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `launch_background`.
    var launch_background: RswiftResources.ImageResource { .init(name: "launch_background", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `onb_first_training`.
    var onb_first_training: RswiftResources.ImageResource { .init(name: "onb_first_training", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `onb_fourth_training`.
    var onb_fourth_training: RswiftResources.ImageResource { .init(name: "onb_fourth_training", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `onb_second_training`.
    var onb_second_training: RswiftResources.ImageResource { .init(name: "onb_second_training", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `onb_third_training`.
    var onb_third_training: RswiftResources.ImageResource { .init(name: "onb_third_training", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `settings_arrow`.
    var settings_arrow: RswiftResources.ImageResource { .init(name: "settings_arrow", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `settings_policy_icon`.
    var settings_policy_icon: RswiftResources.ImageResource { .init(name: "settings_policy_icon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `settings_rate_icon`.
    var settings_rate_icon: RswiftResources.ImageResource { .init(name: "settings_rate_icon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `settings_reset_icon`.
    var settings_reset_icon: RswiftResources.ImageResource { .init(name: "settings_reset_icon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `settings_share_icon`.
    var settings_share_icon: RswiftResources.ImageResource { .init(name: "settings_share_icon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `training_distance_icon`.
    var training_distance_icon: RswiftResources.ImageResource { .init(name: "training_distance_icon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `training_height_icon`.
    var training_height_icon: RswiftResources.ImageResource { .init(name: "training_height_icon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `training_speed_icon`.
    var training_speed_icon: RswiftResources.ImageResource { .init(name: "training_speed_icon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `training_time_icon`.
    var training_time_icon: RswiftResources.ImageResource { .init(name: "training_time_icon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
  }

  /// This `_R.info` struct is generated, and contains static references to 1 properties.
  struct info {
    let bundle: Foundation.Bundle
    var uiApplicationSceneManifest: uiApplicationSceneManifest { .init(bundle: bundle) }

    func uiApplicationSceneManifest(bundle: Foundation.Bundle) -> uiApplicationSceneManifest {
      .init(bundle: bundle)
    }

    struct uiApplicationSceneManifest {
      let bundle: Foundation.Bundle

      let uiApplicationSupportsMultipleScenes: Bool = false

      var _key: String { bundle.infoDictionaryString(path: ["UIApplicationSceneManifest"], key: "_key") ?? "UIApplicationSceneManifest" }
      var uiSceneConfigurations: uiSceneConfigurations { .init(bundle: bundle) }

      func uiSceneConfigurations(bundle: Foundation.Bundle) -> uiSceneConfigurations {
        .init(bundle: bundle)
      }

      struct uiSceneConfigurations {
        let bundle: Foundation.Bundle
        var _key: String { bundle.infoDictionaryString(path: ["UIApplicationSceneManifest", "UISceneConfigurations"], key: "_key") ?? "UISceneConfigurations" }
        var uiWindowSceneSessionRoleApplication: uiWindowSceneSessionRoleApplication { .init(bundle: bundle) }

        func uiWindowSceneSessionRoleApplication(bundle: Foundation.Bundle) -> uiWindowSceneSessionRoleApplication {
          .init(bundle: bundle)
        }

        struct uiWindowSceneSessionRoleApplication {
          let bundle: Foundation.Bundle
          var defaultConfiguration: defaultConfiguration { .init(bundle: bundle) }

          func defaultConfiguration(bundle: Foundation.Bundle) -> defaultConfiguration {
            .init(bundle: bundle)
          }

          struct defaultConfiguration {
            let bundle: Foundation.Bundle
            var uiSceneConfigurationName: String { bundle.infoDictionaryString(path: ["UIApplicationSceneManifest", "UISceneConfigurations", "UIWindowSceneSessionRoleApplication"], key: "UISceneConfigurationName") ?? "Default Configuration" }
            var uiSceneDelegateClassName: String { bundle.infoDictionaryString(path: ["UIApplicationSceneManifest", "UISceneConfigurations", "UIWindowSceneSessionRoleApplication"], key: "UISceneDelegateClassName") ?? "$(PRODUCT_MODULE_NAME).SceneDelegate" }
          }
        }
      }
    }
  }

  /// This `_R.file` struct is generated, and contains static references to 1 resource files.
  struct file {
    let bundle: Foundation.Bundle

    /// Resource file `Training.plist`.
    var trainingPlist: RswiftResources.FileResource { .init(name: "Training", pathExtension: "plist", bundle: bundle, locale: LocaleReference.none) }
  }
}